/** Shared Mongo product document for integration tests (satisfies strict ProductSchema). */

function metricTrend(value = 0) {
  return {
    direction: 'stable' as const,
    changePercent: 0,
    windows: [{ label: 'Now', daysAgo: 0, monthsAgo: 0, value }],
  };
}

export function minimalTestProduct(
  overrides: Record<string, unknown> = {},
): Record<string, unknown> {
  const now = new Date();
  return {
    externalId: 'test-ext-1',
    source: 'tiktok',
    status: 'active',
    title: 'Test Product',
    normalizedTitle: 'test product',
    description: 'Test product description used in integration tests.',
    hashtags: [] as string[],
    categoryL1: 'Beauty & Personal Care',
    categoryL2: 'Skincare',
    categoryL3: 'Face Serums',
    categoryPath: 'Beauty & Personal Care > Skincare > Face Serums',
    primaryImageUrl: 'https://example.com/product.jpg',
    imageUrls: ['https://example.com/product.jpg'],
    price: 19.99,
    currency: 'USD',
    priceTrend: metricTrend(19.99),
    suppliers: [] as unknown[],
    rating: 4.5,
    reviewCount: 12,
    reviews: [] as unknown[],
    ratingSources: [] as unknown[],
    soldCount: 300,
    totalSales: 300,
    totalGmv: 1500,
    salesHistory: [] as unknown[],
    salesTrend: metricTrend(300),
    revenueHistory: [] as unknown[],
    revenueTrend: metricTrend(1500),
    storeGmv: 1000,
    storeTotalSales: 50,
    viewCount: 5000,
    likeCount: 200,
    commentCount: 20,
    shareCount: 10,
    engagementRate: 4.6,
    primaryCreator: {
      handle: 'testcreator',
      displayName: 'Test Creator',
      region: 'US',
      verified: false,
      tiktokPostUrl: 'https://www.tiktok.com/@testcreator/video/1',
      primaryImageUrl: '',
      avatarUrl: '',
    },
    aiIntelligence: {
      confidence: 80,
      confidenceReason: 'Test fixture',
      brand: 'Test Brand',
      buyingSentimentScore: 70,
      buyingSentimentReason: 'Positive test sentiment',
      extractedAt: now,
      niche: 'test',
      productType: 'evergreen',
      priceBand: 'mid-range',
      audience: ['testers'],
      categoryKeywords: [] as string[],
      problemStatement: 'Test problem',
      valueStatement: 'Test value',
      reviewSummary: { summary: 'Test reviews', generatedAt: now },
      marketingAnalysis: {
        primaryGender: 'unisex',
        topAgeGroups: ['18-24'],
        topRegions: ['US'],
        accessibilityTags: [] as string[],
        lifestyleSegments: [] as string[],
        incomeLevel: 'mid-range',
        purchaseIntent: 'considered',
        contentFormat: 'review',
        marketingInsight: 'Test insight',
        angles: [] as unknown[],
        analyzedAt: now,
      },
    },
    trends: {
      engagement: {
        score: 3,
        direction: 'stable',
        reason: '',
        isTrending: false,
        calculatedAt: now,
      },
    },
    discoverySections: [] as string[],
    shopName: 'Test Shop',
    shopUrl: 'https://example.com/shop',
    shopAvatarUrl: 'https://example.com/shop-avatar.jpg',
    shopFollowers: 500,
    postUrl: 'https://www.tiktok.com/@testcreator/video/1',
    postCreatedAt: now.toISOString(),
    publishedAt: now,
    productUrl: 'https://example.com/product',
    accountHandle: 'testshop',
    accountKind: 'store',
    market: 'US',
    relatedVideosCount: 0,
    creativeCounts: { ads: 0, organic: 0, reviews: 0, total: 0 },
    validationStatus: 'valid',
    lastIngestedAt: now,
    dataSourceUpdatedAt: now,
    ...overrides,
  };
}
